In [1]:
# Installing openai
#!pip install gym
#!pip install -e '.[atari]'

In [3]:
import numpy as np
import tensorflow as tf
import gym
import random

In [4]:
# Launch cart pole

env = gym.make('CartPole-v0')
env.reset()
for _ in range(100):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

C:\Users\Hippolyte Moulle\Anaconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [5]:
# Launch a few cart poles with observation, reward, done, info

env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.03588017  0.04328726  0.0282958  -0.00828636]
[ 0.03674591  0.23799222  0.02813007 -0.29190904]
[ 0.04150576  0.43270203  0.02229189 -0.57558905]
[ 0.0501598   0.62750451  0.01078011 -0.8611669 ]
[ 0.06270989  0.82247801 -0.00644323 -1.15044087]
[ 0.07915945  0.62744074 -0.02945205 -0.85978532]
[ 0.09170826  0.43273204 -0.04664776 -0.5765066 ]
[ 0.1003629   0.62847576 -0.05817789 -0.88351224]
[ 0.11293242  0.82433745 -0.07584813 -1.19390237]
[ 0.12941917  1.02035528 -0.09972618 -1.50936174]
[ 0.14982627  1.21653441 -0.12991341 -1.83143927]
[ 0.17415696  1.02306836 -0.1665422  -1.58177287]
[ 0.19461833  1.21973475 -0.19817766 -1.92142818]
Episode finished after 13 timesteps
[ 0.02498231 -0.01865627 -0.00603112 -0.02455114]
[ 0.02460919 -0.21369121 -0.00652215  0.26622281]
[ 0.02033537 -0.01847678 -0.00119769 -0.0285101 ]
[ 0.01996583 -0.21358154 -0.00176789  0.26379471]
[ 0.0156942  -0.0184344   0.003508   -0.02944531]
[ 0.01532551 -0.21360648  0.0029191   0.26434237]
[ 0.01105338 -

[ 0.16950192  0.5514272  -0.20585395 -1.09184849]
Episode finished after 14 timesteps
[-0.03208071  0.04762884  0.00024582 -0.03319367]
[-0.03112814  0.24274726 -0.00041806 -0.32579903]
[-0.02627319  0.43787516 -0.00693404 -0.61861377]
[-0.01751569  0.24285075 -0.01930631 -0.32812277]
[-0.01265867  0.04800889 -0.02586877 -0.04159016]
[-0.01169849 -0.14673274 -0.02670057  0.24281998]
[-0.01463315  0.04876023 -0.02184417 -0.05816398]
[-0.01365794 -0.14604182 -0.02300745  0.2275477 ]
[-0.01657878 -0.34082754 -0.0184565   0.51288537]
[-0.02339533 -0.53568474 -0.00819879  0.79969548]
[-0.03410903 -0.73069327  0.00779512  1.08978803]
[-0.04872289 -0.92591711  0.02959088  1.38490663]
[-0.06724123 -0.7311764   0.05728901  1.10162189]
[-0.08186476 -0.9270034   0.07932145  1.41171424]
[-0.10040483 -0.73294935  0.10755573  1.14484448]
[-0.11506382 -0.92929911  0.13045262  1.46922765]
[-0.1336498  -1.1257536   0.15983718  1.79964988]
[-0.15616487 -1.32226188  0.19583017  2.13744733]
Episode finish

[-0.00335856 -0.03392328  0.01041005  0.04418804]
[-0.00403703  0.16104786  0.01129381 -0.24519232]
[-0.00081607  0.3560067   0.00638997 -0.53429162]
[ 0.00630406  0.16079547 -0.00429587 -0.23960212]
[ 0.00951997 -0.03426485 -0.00908791  0.05172268]
[ 0.00883468  0.16098623 -0.00805346 -0.24381365]
[ 0.0120544  -0.03401977 -0.01292973  0.04631818]
[ 0.01137401  0.16128517 -0.01200337 -0.25041599]
[ 0.01459971 -0.03366333 -0.01701169  0.03845679]
[ 0.01392644 -0.22853725 -0.01624255  0.32572419]
[ 0.0093557  -0.42342422 -0.00972807  0.61324098]
[ 0.00088721 -0.22816769  0.00253675  0.31751003]
[-0.00367614 -0.42332568  0.00888695  0.61099188]
[-0.01214265 -0.22832906  0.02110679  0.32112124]
[-0.01670924 -0.42374513  0.02752922  0.62038499]
[-0.02518414 -0.22901825  0.03993692  0.33649791]
[-0.0297645  -0.03448673  0.04666687  0.05667162]
[-0.03045424  0.15993611  0.04780031 -0.22093005]
[-0.02725552 -0.03583534  0.04338171  0.08643965]
[-0.02797222 -0.23155142  0.0451105   0.39248778]


In [6]:
# Action space and observation state

print(env.action_space)
print(env.observation_space)


# Box's bounds

print(env.observation_space.high)
print(env.observation_space.low)


# Space

from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

Discrete(2)
Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [7]:
print(env.action_space.n)
# print(env.observation_space.n) --> no number of states because it is continuous and infinite

2


In [8]:
# Taxi v2:

env = gym.make("Taxi-v2")
env.render()

DeprecatedEnv: Env Taxi-v2 not found (valid versions include ['Taxi-v3'])

In [8]:
# Hyperparameters:

max_parties = 50000
test_parties = 100
max_steps = 99

alpha_rate = 0.1
gamma_rate = 0.9

epsilon = 1.0
epsilon_max = 1.0
epsilon_min = 0.01
decay_rate = 0.1

In [9]:
# Defining Q table at 0

action_size = env.action_space.n
state_size = env.observation_space.n

Q_table = np.zeros((state_size, action_size))
print(Q_table.shape)

(500, 6)


In [10]:
# Training algorithm

for i in range(max_parties):
    
    # Initialization
    state = env.reset()
    
    # Algorithm for each game
    for ite in range(max_steps):

        # Exploration or exploitation
        explo = random.uniform(0, 1)
        if explo > epsilon:
            action = np.argmax(Q_table[state, :])
        else:
            action = env.action_space.sample()

        # Updating Q table
        new_state, reward, done, info = env.step(action)
        Q_table[state, action] = Q_table[state, action] + alpha_rate * (reward + gamma_rate*np.max(Q_table[new_state, :]) - Q_table[state, action])
        # Updating state
        state = new_state

        # Breaking if necessary
        if done == True:
            break

    # Decreasing epsilon
    epsilon = epsilon_min + (epsilon_max - epsilon_min) * np.exp(-decay_rate * i)
    
    # Print improvement
    if np.mod(i+1, np.floor(max_parties/10)) == 0:
        print("Iteration %.0f out of %.0f." %(i+1, max_parties))

Iteration 5000 out of 50000.
Iteration 10000 out of 50000.
Iteration 15000 out of 50000.
Iteration 20000 out of 50000.
Iteration 25000 out of 50000.
Iteration 30000 out of 50000.
Iteration 35000 out of 50000.
Iteration 40000 out of 50000.
Iteration 45000 out of 50000.
Iteration 50000 out of 50000.


In [11]:
# Testing algorithm:

rewards = np.zeros((test_parties, 1))

for i in range(test_parties):
    
    # Initialization
    state = env.reset()
    reward_temp = 0
    
    # Main algorithm
    for ite in range(max_steps):
        action = np.argmax(Q_table[state, :])
        state, reward, done, info = env.step(action)
        reward_temp = reward_temp + reward
        if done == True:
            break
    
    # Uddating rewards
    rewards[i] = reward_temp
    
print("Mean reward is %.2f, maximum reward is %.2f, minimum reward is %.2f." %(np.mean(rewards), np.max(rewards), np.min(rewards)))

Mean reward is 8.54, maximum reward is 14.00, minimum reward is 4.00.


In [12]:
# Plotting algorithm

state = env.reset()
for ite in range(max_steps):
    env.render()
    action = np.argmax(Q_table[state, :])
    state, reward, done, info = env.step(action)
    reward_temp = reward_temp + reward
    if done == True:
        break
env.close()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : :_: : |
| | : | : |
|Y| : |B: |

In [15]:
# Frozen Lake v0



# Load game
env = gym.make("FrozenLake-v0")
env.render()



# Hyperparameters:

max_parties = 15000
test_parties = 100
max_steps = 99

alpha_rate = 0.8
gamma_rate = 0.95

epsilon = 1.0
epsilon_max = 1.0
epsilon_min = 0.01
decay_rate = 0.005



# Defining Q table at 0

action_size = env.action_space.n
state_size = env.observation_space.n

Q_table = np.zeros((state_size, action_size))
print(Q_table.shape)



# Training algorithm

for i in range(max_parties):
    
    # Initialization
    state = env.reset()
    
    # Algorithm for each game
    for ite in range(max_steps):

        # Exploration or exploitation
        explo = random.uniform(0, 1)
        if explo > epsilon:
            action = np.argmax(Q_table[state, :])
        else:
            action = env.action_space.sample()

        # Updating Q table
        new_state, reward, done, info = env.step(action)
        Q_table[state, action] = Q_table[state, action] + alpha_rate * (reward + gamma_rate*np.max(Q_table[new_state, :]) - Q_table[state, action])
        # Updating state
        state = new_state

        # Breaking if necessary
        if done == True:
            break

    # Decreasing epsilon
    epsilon = epsilon_min + (epsilon_max - epsilon_min) * np.exp(-decay_rate * i)
    
    # Print improvement
    if np.mod(i+1, np.floor(max_parties/10)) == 0:
        print("Iteration %.0f out of %.0f." %(i+1, max_parties))
        

        
# Testing algorithm:

rewards = np.zeros((test_parties, 1))

for i in range(test_parties):
    
    # Initialization
    state = env.reset()
    reward_temp = 0
    
    # Main algorithm
    for ite in range(max_steps):
        action = np.argmax(Q_table[state, :])
        state, reward, done, info = env.step(action)
        reward_temp = reward_temp + reward
        if done == True:
            break
    
    # Uddating rewards
    rewards[i] = reward_temp
    
print("Mean reward is %.2f, maximum reward is %.2f, minimum reward is %.2f." %(np.mean(rewards), np.max(rewards), np.min(rewards)))



# Plotting algorithm

state = env.reset()
env.render()
for ite in range(max_steps):
    action = np.argmax(Q_table[state, :])
    state, reward, done, info = env.step(action)
    reward_temp = reward_temp + reward
    env.render()
    if done == True:
        break
env.close()


SFFF
FHFH
FFFH
HFFG
(16, 4)
Iteration 1500 out of 15000.
Iteration 3000 out of 15000.
Iteration 4500 out of 15000.
Iteration 6000 out of 15000.
Iteration 7500 out of 15000.
Iteration 9000 out of 15000.
Iteration 10500 out of 15000.
Iteration 12000 out of 15000.
Iteration 13500 out of 15000.
Iteration 15000 out of 15000.
Mean reward is 0.56, maximum reward is 1.00, minimum reward is 0.00.

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF


In [14]:
print(Q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
